version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: carelulu_todo
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
